[package]
name = "websearch"
version = "0.1.1"
edition = "2021"
description = "Plugin to search with your preferred search-engine"
license = "GPLv3"
homepage = "https://github.com/anyrun-org/plugin-websearch"
repository = "https://github.com/anyrun-org/plugin-websearch"
readme = "README.md"
author = ["Kirottu"]

[lib]
crate-type = ["cdylib"]

[dependencies]
abi_stable = "0.11.1"
anyrun-plugin = "0.1.1"
ron = "0.8.0"
serde = { version = "1.0.152", features = ["derive"] }
strum = "0.25.0"
strum_macros = "0.25.1"
urlencoding = "2.1.3"
